SET SESSION FOREIGN_KEY_CHECKS=0;


/* Create Tables */

-- 包含个人及公共文章
CREATE TABLE ARTICLE
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	TITLE VARCHAR(200),
	SUMMARY VARCHAR(500),
	CONTENT LONGTEXT,
	CTIME VARCHAR(50),
	PTIME VARCHAR(50),
	EMPID BIGINT NOT NULL,
	-- 供公告通知使用
	STARTTIME VARCHAR(50),
	-- yyyy-MM-dd HH:mm:ss
	ENDTIME VARCHAR(50),
	ACTCATEID BIGINT NOT NULL,
	-- 0：私有 1:指定范围 2 公开
	VRANGE SMALLINT,
	-- 0非通告1 通告
	-- 
	-- 以此拆分充文章及通告两个功能
	NOTICE SMALLINT,
	PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8;


CREATE TABLE ARTICLECATE
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(50),
	NUM VARCHAR(20),
	REMARK VARCHAR(100),
	PID BIGINT NOT NULL,
	PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8;


CREATE TABLE ARTICLERANGE
(
	EMPID BIGINT NOT NULL,
	-- 如角色、部门、机构、人员id
	OBJID BIGINT,
	-- 0人员1角色2部门3机构
	OBJTYPE SMALLINT
) DEFAULT CHARACTER SET utf8;


CREATE TABLE ARTICLEREAD
(
	ARTID BIGINT NOT NULL,
	EMPID BIGINT NOT NULL
) DEFAULT CHARACTER SET utf8;


CREATE TABLE DOCCATE
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(50),
	NUM VARCHAR(20),
	REMARK VARCHAR(100),
	PID BIGINT NOT NULL,
	PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8;


CREATE TABLE DOCRANGE
(
	EMPID BIGINT NOT NULL,
	-- 如角色、部门、机构、人员id
	OBJID BIGINT,
	-- 0人员1角色2部门3机构
	OBJTYPE SMALLINT
) DEFAULT CHARACTER SET utf8;


CREATE TABLE DOCUMENT
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	TITLE VARCHAR(200),
	SUMMARY VARCHAR(500),
	CTIME VARCHAR(50),
	PTIME VARCHAR(50),
	-- 供公告通知使用
	STARTTIME VARCHAR(50),
	-- yyyy-MM-dd HH:mm:ss
	ENDTIME VARCHAR(50),
	DOCCATEID BIGINT NOT NULL,
	-- 0：私有 1:指定范围 2 公开
	VRANGE SMALLINT,
	EMPID BIGINT NOT NULL,
	-- 多文件格式为:
	-- filename:path;filename:path;
	ATTACHMENT VARCHAR(500),
	PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8;


CREATE TABLE EMPLOYEE
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	FULLNAME VARCHAR(50) NOT NULL,
	-- 男 女
	GENDER VARCHAR(2) DEFAULT '男' NOT NULL,
	USERNO VARCHAR(20) NOT NULL UNIQUE,
	PWD VARCHAR(50) NOT NULL,
	BIRTHDAY VARCHAR(20) NOT NULL,
	PHONE VARCHAR(20),
	TELPHONE VARCHAR(30),
	ADDR VARCHAR(100),
	FNAMEPY VARCHAR(50),
	WORKTIME VARCHAR(30),
	NATION VARCHAR(10) DEFAULT '汉',
	IDCARD VARCHAR(20),
	HOMETOWN SMALLINT,
	DIPLOMA SMALLINT,
	PHOTO VARCHAR(50),
	PARTMENTID BIGINT NOT NULL,
	-- 对应公司及分公司
	ORGID BIGINT,
	-- 0准备中、1制作中、2已出品
	STAT SMALLINT DEFAULT 0,
	REMARK VARCHAR(200),
	-- 可以对厨师等技师做推广介绍用
	RESUME LONGTEXT,
	PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8;


CREATE TABLE MENU
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(20) NOT NULL,
	URL VARCHAR(50) NOT NULL,
	-- 菜单类型：0 菜单 1：按钮
	TYPE SMALLINT,
	MENULEVEL SMALLINT DEFAULT 0,
	ICON VARCHAR(50),
	ORDERNUM INT DEFAULT 0,
	SAFECODE VARCHAR(20),
	PID BIGINT,
	-- 0tab页 1窗口
	TARGET SMALLINT,
	REL VARCHAR(30),
	-- 0禁用1可用
	ENABLE SMALLINT DEFAULT 1,
	REMARK VARCHAR(255),
	PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8;


CREATE TABLE ORGANIZATION
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(30),
	ADDR VARCHAR(50),
	PICID BIGINT,
	SORTNUM SMALLINT,
	REMARK VARCHAR(100),
	NUM VARCHAR(20),
	PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8;


CREATE TABLE PARTMENT
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(50),
	REMARK VARCHAR(250),
	PICID BIGINT,
	ORGID BIGINT,
	NUM VARCHAR(20),
	PID BIGINT NOT NULL,
	PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8;


CREATE TABLE POWERMENU
(
	-- 对用户、机构、部门、角色来进行配置
	OBJID BIGINT NOT NULL,
	-- 0：用户
	-- 1：角色
	-- 2：部门 
	-- 3：:组织机构
	-- 4:用户自设常用
	TYPE SMALLINT(1) NOT NULL,
	MENUID BIGINT NOT NULL
) DEFAULT CHARACTER SET utf8;


CREATE TABLE PRINTER
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	IP VARCHAR(20),
	PORT VARCHAR(10),
	TYPE SMALLINT,
	FC VARCHAR(20),
	-- 0不可用
	-- 1 可用
	STAT SMALLINT DEFAULT 1,
	PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8;


-- 角色和职务可以公用
CREATE TABLE ROLE
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(20) NOT NULL,
	REMARK VARCHAR(255),
	PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8;


-- 包含 菜肴分类、酒水分类
CREATE TABLE SYSTEMPARAM
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(20) NOT NULL,
	VAL VARCHAR(20) NOT NULL,
	-- 具体按系统设计要求来定
	TYPE SMALLINT,
	SORTNUM SMALLINT DEFAULT 0,
	REMARK VARCHAR(200),
	PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8;


CREATE TABLE USERROLE
(
	USERID BIGINT NOT NULL,
	ROLEID BIGINT NOT NULL
) DEFAULT CHARACTER SET utf8;


CREATE TABLE WAGEPAY
(
	ID BIGINT NOT NULL,
	EMPID BIGINT,
	WAGES INT,
	SDATE VARCHAR(20),
	EDATE VARCHAR(20),
	AMOUNT DECIMAL(10,2),
	PAYDATE VARCHAR(20),
	OPERATER BIGINT,
	PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8;


CREATE TABLE WAGES
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	WAGES INT,
	-- 格式为YYYYMM
	ENMONTH VARCHAR(10),
	REMARK VARCHAR(250),
	OPERATER BIGINT,
	CTIME VARCHAR(50),
	EMPID BIGINT NOT NULL,
	PRIMARY KEY (ID)
) DEFAULT CHARACTER SET utf8;



/* Create Indexes */

CREATE INDEX IDX_EMPLOYEE_PWD ON EMPLOYEE (PWD ASC);
CREATE INDEX IDX_EMPLOYEE_USERNO ON EMPLOYEE (USERNO ASC);
CREATE INDEX IDX_EMP_PYNAME ON EMPLOYEE (FNAMEPY ASC);



